/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    CommentItem: typeof import('./components/suggestion/CommentItem.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    LoginAside: typeof import('./components/auth/LoginAside.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    NotificationCard: typeof import('./components/NotificationCard.vue')['default']
    ResizableDraggableImage: typeof import('./components/editor/ResizableDraggableImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusUpdateDialog: typeof import('./components/suggestion/StatusUpdateDialog.vue')['default']
    SuggestionCard: typeof import('./components/suggestion/SuggestionCard.vue')['default']
    SuggestionCommentsCard: typeof import('./components/suggestion/SuggestionCommentsCard.vue')['default']
    SuggestionDetailsCard: typeof import('./components/suggestion/SuggestionDetailsCard.vue')['default']
    SuggestionEventsCard: typeof import('./components/suggestion/SuggestionEventsCard.vue')['default']
    SuggestionsList: typeof import('./components/suggestion/SuggestionsList.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
  }
}
