/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/category/': RouteRecordInfo<'/category/', '/category', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/suggestion/': RouteRecordInfo<'/suggestion/', '/suggestion', Record<never, never>, Record<never, never>>,
    '/suggestion/[id]': RouteRecordInfo<'/suggestion/[id]', '/suggestion/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/suggestion/create': RouteRecordInfo<'/suggestion/create', '/suggestion/create', Record<never, never>, Record<never, never>>,
    '/suggestion/edit/[id]': RouteRecordInfo<'/suggestion/edit/[id]', '/suggestion/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
